server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stu?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.org.continent.entity
  typeEnumsPackage: cn.org.continent.entity.enums
  global-config:
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 3
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    #mybatis-plus.global-config.sql-injector=com.baomidou.mybatisplus.mapper.LogicSqlInjector
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #最好使用自定义bean注入
    logic-delete-value: 0
    logic-not-delete-value: 1
    #刷新mapper 调试神器
    refresh-mapper: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句，调试用

#2.3.1版本往上（不包括）
#mybatis-plus:
  #mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: cn.org.continent.entity
  #typeEnumsPackage: cn.org.continent.entity.enums
  #global-config:
    # 数据库相关配置
    #db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      #id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #field-strategy: not_empty
      #驼峰下划线转换
      #column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 0
      #logic-not-delete-value: 1
      #db-type: mysql
    #刷新mapper 调试神器
    #refresh: true
  # 原生配置
  #configuration:
    #map-underscore-to-camel-case: true
    #cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句，调试用